
import { GoogleGenAI, Type, Modality, GenerateContentResponse } from "@google/genai";

if (!process.env.API_KEY) {
  throw new Error("API_KEY environment variable not set");
}

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

const fileToBase64 = (file: File): Promise<string> => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = () => resolve((reader.result as string).split(',')[1]);
    reader.onerror = (error) => reject(error);
  });
};

export const suggestStyle = async (imageBase64: string, mimeType: string): Promise<string> => {
  try {
    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: {
        parts: [
          {
            inlineData: {
              mimeType: mimeType,
              data: imageBase64,
            },
          },
          {
            text: `Analyse l'apparence de cette personne et suggère le style de shooting photo professionnel le plus adapté à sa personnalité et à sa tenue. Les styles possibles sont : Mode, Corporate, Artistique, Lifestyle.`,
          },
        ],
      },
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            style: {
              type: Type.STRING,
              description: "Le style de photo suggéré en français (e.g., 'Corporate')."
            },
          },
          required: ["style"],
        },
      },
    });

    const jsonString = response.text.trim();
    const result = JSON.parse(jsonString);
    return result.style;
  } catch (error) {
    console.error("Error suggesting style:", error);
    throw new Error("Failed to suggest a style. Please try again.");
  }
};

export const enhanceImage = async (imageBase64: string, mimeType: string, style: string): Promise<string> => {
  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              data: imageBase64,
              mimeType: mimeType,
            },
          },
          {
            text: `Améliore cette photo pour un rendu de type shooting studio professionnel dans le style "${style}". Améliore la netteté, l'éclairage et le réalisme général pour un aspect haut de gamme. **Conserve impérativement le visage, les traits et l'expression de la personne sans aucune modification.** Le résultat doit être naturel et professionnel.`,
          },
        ],
      },
      config: {
        responseModalities: [Modality.IMAGE, Modality.TEXT],
      },
    });

    if (response.candidates && response.candidates[0].content.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
          return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
        }
      }
    }
    
    throw new Error("No image was generated by the model.");
  } catch (error) {
    console.error("Error enhancing image:", error);
    throw new Error("Failed to enhance the image. Please try again.");
  }
};
